cat JsManager.js > main.js
echo "\n" >> main.js
cat src/LAppDefine.js >> main.js
echo "\n" >> main.js
cat src/live2d.js >> main.js
echo "\n" >> main.js
cat src/LAppLive2DManager.js >> main.js
echo "\n" >> main.js
cat src/Live2DFramework.js >> main.js
echo "\n" >> main.js
cat src/LAppModel.js >> main.js
echo "\n" >> main.js
cat src/MatrixStack.js >> main.js
echo "\n" >> main.js
cat src/ModelSettingJson.js >> main.js
echo "\n" >> main.js
cat src/PlatformManager.js >> main.js
echo "\n" >> main.js
cat src/SampleApp.js >> main.js
echo "\n" >> main.js
cat tips/tips.js >> main.js
echo "\n" >> main.js

cat live2d.css > main.css
echo "\n" >> main.css
cat tips.css >> main.css
echo "\n" >> main.css
